<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <UserSecretsId>gpay-banking-absa-capi</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GPay.Banking.Contracts\GPay.Banking.Contracts.csproj" />
    <ProjectReference Include="..\GPay.Banking.Infrastructure\GPay.Banking.Infrastructure.csproj" />
    <ProjectReference Include="..\GPay.Banking.Persistence\GPay.Banking.Persistence.csproj" />
  </ItemGroup>

</Project>
